<?php
namespace App\Enums;

enum ApiSlug: string
{
    // Login
    case LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case NEED_SIGN_IN = 'NEED_SIGN_IN';
    case LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
    case OTP_SENT = 'OTP_SENT';
    case OTP_INVALID = 'OTP_INVALID';
    case OTP_SEND = 'OTP_SEND';
    case OTP_EXPIRED = 'OTP_EXPIRED';
    case VERIFIED_SUCCESSFULLY = 'VERIFIED_SUCCESSFULLY';
    case MOBILE_REQUIRED = 'MOBILE_REQUIRED';

    // Form Validate
    case VALIDATION_ERROR = 'VALIDATION_ERROR';


    // Profile
    case PROFILE_UPDATED = 'PROFILE_UPDATED';
    case PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';

    // Financial
    case DEBT_ADDED = 'DEBT_ADDED';
    case DEBT_REMOVED = 'DEBT_REMOVED';
    case DEBT_REMOVED_FAILED = 'DEBT_REMOVED_FAILED';
    case DEBT_UPDATED = 'DEBT_UPDATED';
    case DEBT_FOUND = 'DEBT_FOUND';
    case DEBT_NOTFOUND = 'DEBT_NOTFOUND';
    case DEBT_UPDATED_FAILED = 'DEBT_UPDATED_FAILED';
    case DEBT_STORE_FAILED = 'DEBT_STORE_FAILED';
    case CLAIM_ADDED = 'CLAIM_ADDED';
    case CLAIM_UPDATED = 'CLAIM_UPDATED';
    case CLAIM_NOTFOUND = 'CLAIM_NOTFOUND';
    case CLAIM_UPDATED_FAILED = 'CLAIM_UPDATED_FAILED';
    case CLAIM_REMOVED = 'CLAIM_REMOVED';

    //Regigius
    case PRAYER_CREATED = 'PRAYER_CREATED';
    case PRAYER_CREATED_FAILED = 'PRAYER_CREATED_FAILED';
    case PRAYER_REMOVED = 'PRAYER_REMOVED';
    case PRAYER_REMOVE_FAILED = 'PRAYER_REMOVE_FAILED';
    case PRAYER_UPDATED = 'PRAYER_UPDATED';
    case PRAYER_UPDATE_FAILED = 'PRAYER_UPDATE_FAILED';

    case FASTING_UPDATE_FAILED = 'FASTING_UPDATE_FAILED';
    case FASTING_UPDATED = 'FASTING_UPDATED';

    case KHUMS_NOTFOUND = 'KHUMS_NOTFOUND';
    case KHUMS_FOUND = 'KHUMS_FOUND';
    case KHUMS_ADDED = 'KHUMS_ADDED';
    case KHUMS_REMOVED = 'KHUMS_REMOVED';
    case KHUMS_ERROR = 'KHUMS_ERROR';
    case KHUMS_REMOVED_FAILED = 'KHUMS_REMOVED_FAILED';
    case KHUMS_UPDATE_FAILED = 'KHUMS_UPDATE_FAILED';
    case KHUMS_UPDATED = 'KHUMS_UPDATED';


    case ZAKAT_UPDATED = 'ZAKAT_UPDATED';
    case ZAKAT_REMOVED_FAILED = 'ZAKAT_REMOVED_FAILED';
    case ZAKAT_REMOVED = 'ZAKAT_REMOVED';
    case ZAKAT_NOTFOUND = 'ZAKAT_NOTFOUND';
    case ZAKAT_ERROR = 'ZAKAT_ERROR';
    case ZAKAT_ADDED = 'ZAKAT_ADDED';
    case ZAKAT_UPDATE_FAILED = 'ZAKAT_UPDATE_FAILED';

    // General
    case UNAUTHORIZED = 'UNAUTHORIZED';
    case SERVER_ERROR = 'SERVER_ERROR';
    case NOTIFICATION_NOTFOUND = 'NOTIFICATION_NOTFOUND';
    case NOTIFICATION_FOUND = 'NOTIFICATION_FOUND';
    case NOTIFICATION_STATE = 'NOTIFICATION_STATE';
    case DATABASE_ERROR = 'DATABASE_ERROR';
}
